require: rubocop-rails

AllCops:
  NewCops: enable
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Metrics/AbcSize:
  Exclude:
    - 'db/**/*.rb'
    - 'test/**/*.rb'
Metrics/BlockLength:
  Max: 80
  Exclude:
    - '**/*.rake'
    - 'test/**/*.rb'
Layout/LineLength:
  Max: 150
Metrics/MethodLength:
  Max: 30
Rails/SkipsModelValidations:
  Exclude:
    - 'db/**/*.rb'
Style/Documentation:
  Exclude:
    - 'db/**/*.rb'
    - 'test/**/*.rb'
Style/WordArray:
  EnforcedStyle: brackets
Style/RegexpLiteral:
  AllowInnerSlashes: true
Style/SymbolArray:
  EnforcedStyle: brackets
