# Runs our test suite via Github Actions

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup database
      env:
        DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/rotator_ipa_test
        RAILS_ENV: test
      run: |
        bundle exec rails db:setup
        bundle exec rails db:migrate
    - name: Run tests
      env:
        DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/rotator_ipa_test
        RAILS_ENV: test
      run: bundle exec rails test
